[package]
name = "Adatb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atk = "0.18.0"
cairo = "0.0.4"
soup = "0.5.1"
soup2-sys = "0.2.0"
